### ISSUE TITLE
Where are fetch_val_data_orderly and save_val_result？

### ISSUE THREAD

**Issue by bityangke** [YiyongHuang/S2VT#1]
Thanks very much.
Where are the functions fetch_val_data_orderly and save_val_result in evaluate.py

**Comment by bityangke** [comment]
And also Bi_module

**Comment by YiyongHuang** [comment]
I'm sorry for taking so long to reply to you, I have uploaded a wrong utils.py file and import a wrong module before, I have reupload the right utils.py now. And about the bi_module, when I do some experiment I find that the implement of bidirectional_LSTM in pytorch exists some problems, and performs very bad, so I removed it, and forgot to change the module, I have edited now. Thank you for your notice.
